name: Rust

on:
  push:
    branches: travis_to_actions

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-postal:
    name: rust-postal
    runs-on: ubuntu-latest
    steps:
      - name: libpostal
        run: |
          sudo apt-get update
          sudo apt-cache search gcc
          sudo apt-get install -y gcc-9.4 libsnappy-dev manpages-fr-extra pkg-config
          export CC="gcc-9.4"
          git clone https://github.com/openvenues/libpostal
          cd libpostal
          ./bootstrap.sh
          ./configure --datadir=$(pwd)/data
          sudo make install
          cd ..
          sudo ldconfig
      - name: deps
        uses: actions/checkout@v2

      - name: rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: check
        uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: check
          args: --verbose --all

      - name: build
        uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: build
          args: --verbose --all

      - name: test
        uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: test
          args: --verbose --all -- --test-threads 1

      - name: bench
        uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: bench


